version: '3'
services:
  thingsboard_cassandra:
    image: thingsboard/tb-cassandra:2.3.1
    ports:
      - "1883:1883"
      - "5683:5683/udp"
      - "9090:9090"
    volumes:
      - "./volumes/thingsboard_data:/data"
      - "./volumes/thingsboard_logs:/var/log/thingsboard"
    restart: always